package com.proit.pe.tabs;

import com.proit.pe.MainFrame;
import com.proit.pe.dao.ExpenditureDao;
import com.proit.pe.entity.Expenditure;
import com.proit.pe.util.DateUtil;
import com.proit.pe.util.MessageBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ListExpendituresPane extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private DefaultTableModel model;

    public ListExpendituresPane(MainFrame mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();

        initTable();

        loadListExpenditure();
    }

    private void initTable() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Tên chi tiêu", "Số tiền", "Loại chi tiêu", "Ngày thêm chi tiêu"});

        tblList.setModel(model);
    }

    private void loadListExpenditure() {
        try {
            ExpenditureDao dao = new ExpenditureDao();

            var list = dao.findAll();

            model.setRowCount(0);

            for (Expenditure item : list) {
                Object[] row = new Object[]{
                    item.getId(),
                    item.getName(),
                    item.getAmount(),
                    item.getTypeName(),
                    DateUtil.toString(item.getCreatedAt())
                };
                model.addRow(row);
            }
            model.fireTableDataChanged();
        } catch (Exception e) {
            MessageBox.showErrorMessage(this, e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ppmList = new javax.swing.JPopupMenu();
        ppmViewDetail = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ppmEdit = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        ppmDelete = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();

        ppmViewDetail.setText("Chi tiết");
        ppmList.add(ppmViewDetail);
        ppmList.add(jSeparator2);

        ppmEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_20.png"))); // NOI18N
        ppmEdit.setText("Chỉnh sửa");
        ppmEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppmEditActionPerformed(evt);
            }
        });
        ppmList.add(ppmEdit);
        ppmList.add(jSeparator3);

        ppmDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_20.png"))); // NOI18N
        ppmDelete.setText("Xoá");
        ppmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppmDeleteActionPerformed(evt);
            }
        });
        ppmList.add(ppmDelete);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/expenditure_32.png"))); // NOI18N
        jLabel1.setText("Danh sách chi tiêu");

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblList.setComponentPopupMenu(ppmList);
        jScrollPane1.setViewportView(tblList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ppmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppmDeleteActionPerformed
        try {
            if (MessageBox.showConfirmMessage(this, "Do you want to delete?")
                    == JOptionPane.NO_OPTION) {
                return;
            }

            ExpenditureDao dao = new ExpenditureDao();

            int selectedRow = tblList.getSelectedRow();

            Object idObj = tblList.getValueAt(selectedRow, 0);
            if (idObj != null) {
                int id = Integer.parseInt(idObj.toString());

                if (dao.delete(id)) {
                    MessageBox.showInformationMessage(this, "Information",
                            "Expenditure is deleted");
                    loadListExpenditure();
                } else {
                    MessageBox.showErrorMessage(this, "Error",
                            "Expenditure can not be deleted");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageBox.showErrorMessage(this, "Error", e.getMessage());
        }
    }//GEN-LAST:event_ppmDeleteActionPerformed

    private void ppmEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppmEditActionPerformed
        int selectedRow = tblList.getSelectedRow();

        Object idObj = tblList.getValueAt(selectedRow, 0);

        if (idObj != null) {
            int id = Integer.parseInt(idObj.toString());

            mainFrame.showEditExpenditure(id);
        }
    }//GEN-LAST:event_ppmEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem ppmDelete;
    private javax.swing.JMenuItem ppmEdit;
    private javax.swing.JPopupMenu ppmList;
    private javax.swing.JMenuItem ppmViewDetail;
    private javax.swing.JTable tblList;
    // End of variables declaration//GEN-END:variables
}
