package com.proit.pe;

import com.proit.pe.dialog.AboutUsDialog;
import com.proit.pe.dialog.LoginDialog;
import com.proit.pe.tabs.AddExpenditurePane;
import com.proit.pe.tabs.AddExpenditureTypePane;
import com.proit.pe.tabs.AddReceiptPane;
import com.proit.pe.tabs.ListExpenditureTypesPane;
import com.proit.pe.tabs.ListExpendituresPane;
import com.proit.pe.tabs.ListReceiptsPane;
import com.proit.pe.tabs.UpdateExpenditurePane;
import com.proit.pe.tabs.UpdateExpenditureTypePane;
import java.awt.event.KeyEvent;


public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnBoard = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        tbrLock = new javax.swing.JButton();
        tbrCloseTab = new javax.swing.JButton();
        tbrAddExpenditure = new javax.swing.JButton();
        tbrListExpenditure = new javax.swing.JButton();
        tbrAddReceipt = new javax.swing.JButton();
        tbrListReceipts = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuLogin = new javax.swing.JMenuItem();
        mnuLogout = new javax.swing.JMenuItem();
        mnuLockup = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuAddExpenditureType = new javax.swing.JMenuItem();
        mnuListExpenditureTypes = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnuAddExpenditure = new javax.swing.JMenuItem();
        mnuListExpenditure = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuAddNewReceipt = new javax.swing.JMenuItem();
        mnuListReceipts = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuAboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý chi tiêu cá nhân");
        setSize(new java.awt.Dimension(1080, 850));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );

        tpnBoard.addTab("Trang Chủ", new javax.swing.ImageIcon(getClass().getResource("/icons/home_32.png")), jPanel1); // NOI18N

        tbrLock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lock_32.png"))); // NOI18N
        tbrLock.setText("Khoá ứng dụng");
        tbrLock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrLock.setMinimumSize(new java.awt.Dimension(60, 60));
        tbrLock.setPreferredSize(new java.awt.Dimension(60, 60));
        tbrLock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrLock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrLockActionPerformed(evt);
            }
        });

        tbrCloseTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close-tab_32.png"))); // NOI18N
        tbrCloseTab.setText("Đóng bớt cửa sổ");
        tbrCloseTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrCloseTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrCloseTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrCloseTabActionPerformed(evt);
            }
        });

        tbrAddExpenditure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_20.png"))); // NOI18N
        tbrAddExpenditure.setText("Thêm Chi Tiêu");
        tbrAddExpenditure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAddExpenditure.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAddExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAddExpenditureActionPerformed(evt);
            }
        });

        tbrListExpenditure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/expenditure_32.png"))); // NOI18N
        tbrListExpenditure.setText("Danh sách chi tiêu");
        tbrListExpenditure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrListExpenditure.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrListExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrListExpenditureActionPerformed(evt);
            }
        });

        tbrAddReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_20.png"))); // NOI18N
        tbrAddReceipt.setText("Tạo biên lai chi tiêu");
        tbrAddReceipt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAddReceipt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAddReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAddReceiptActionPerformed(evt);
            }
        });

        tbrListReceipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/receipt_32.png"))); // NOI18N
        tbrListReceipts.setText("Danh sách biên lai chi tiêu");
        tbrListReceipts.setActionCommand("Danh sách biên chi tiêu");
        tbrListReceipts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrListReceipts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrListReceipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrListReceiptsActionPerformed(evt);
            }
        });

        jMenu1.setMnemonic(KeyEvent.VK_F);
        jMenu1.setText("Tệp");

        mnuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login_20.png"))); // NOI18N
        mnuLogin.setText("Đăng nhập");
        jMenu1.add(mnuLogin);

        mnuLogout.setText("Đăng xuất");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLogout);

        mnuLockup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.META_DOWN_MASK));
        mnuLockup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lock_20.png"))); // NOI18N
        mnuLockup.setMnemonic(KeyEvent.VK_L);
        mnuLockup.setText("Khoá ứng dụng");
        mnuLockup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLockupActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLockup);
        jMenu1.add(jSeparator3);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.META_DOWN_MASK));
        mnuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit_20.png"))); // NOI18N
        mnuExit.setMnemonic(KeyEvent.VK_X);
        mnuExit.setText("Thoát");
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic(KeyEvent.VK_M);
        jMenu2.setText("Quản lý");

        mnuAddExpenditureType.setText("Thêm loại chi tiêu");
        mnuAddExpenditureType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddExpenditureTypeActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAddExpenditureType);

        mnuListExpenditureTypes.setText("Danh sách loại chi tiêu");
        mnuListExpenditureTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListExpenditureTypesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuListExpenditureTypes);
        jMenu2.add(jSeparator8);

        mnuAddExpenditure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_32.png"))); // NOI18N
        mnuAddExpenditure.setText("Thêm chi tiêu");
        mnuAddExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddExpenditureActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAddExpenditure);

        mnuListExpenditure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/expenditure_20.png"))); // NOI18N
        mnuListExpenditure.setText("Danh sách chi tiêu");
        mnuListExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListExpenditureActionPerformed(evt);
            }
        });
        jMenu2.add(mnuListExpenditure);
        jMenu2.add(jSeparator2);

        mnuAddNewReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_32.png"))); // NOI18N
        mnuAddNewReceipt.setText("Tạo biên lai chi tiêu");
        mnuAddNewReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddNewReceiptActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAddNewReceipt);

        mnuListReceipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/receipt_20.png"))); // NOI18N
        mnuListReceipts.setText("Danh sách biên lai chi tiêu");
        mnuListReceipts.setActionCommand("");
        mnuListReceipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListReceiptsActionPerformed(evt);
            }
        });
        jMenu2.add(mnuListReceipts);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Giúp đỡ");

        mnuAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about_20.png"))); // NOI18N
        mnuAboutUs.setText("About Us");
        mnuAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutUsActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAboutUs);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbrAddExpenditure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbrListExpenditure)
                        .addGap(48, 48, 48)
                        .addComponent(tbrAddReceipt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbrListReceipts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbrCloseTab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbrLock, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tpnBoard))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbrLock, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbrAddExpenditure)
                                    .addComponent(tbrListExpenditure)
                                    .addComponent(tbrAddReceipt)
                                    .addComponent(tbrListReceipts))
                                .addComponent(tbrCloseTab)))))
                .addGap(18, 18, 18)
                .addComponent(tpnBoard)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbrAddExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAddExpenditureActionPerformed
        AddExpenditurePane pane = new AddExpenditurePane(this);

        tpnBoard.addTab("Thêm chi tiêu", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrAddExpenditureActionPerformed

    private void tbrCloseTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrCloseTabActionPerformed

        int selectedIndex = tpnBoard.getSelectedIndex();
        if (selectedIndex > 0) {
            tpnBoard.remove(selectedIndex);
        }
    }//GEN-LAST:event_tbrCloseTabActionPerformed

    private void mnuAddExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddExpenditureActionPerformed
        tbrAddExpenditureActionPerformed(evt);
    }//GEN-LAST:event_mnuAddExpenditureActionPerformed

    private void tbrListExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrListExpenditureActionPerformed
        ListExpendituresPane pane = new ListExpendituresPane(this);

        tpnBoard.addTab("Danh chi tiêu", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrListExpenditureActionPerformed

    private void mnuListExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListExpenditureActionPerformed
        tbrListExpenditureActionPerformed(evt);
    }//GEN-LAST:event_mnuListExpenditureActionPerformed

    private void tbrAddReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAddReceiptActionPerformed
        AddReceiptPane pane = new AddReceiptPane();

        tpnBoard.addTab("Thêm biên lai", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrAddReceiptActionPerformed

    private void mnuAddNewReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddNewReceiptActionPerformed
        tbrAddReceiptActionPerformed(evt);
    }//GEN-LAST:event_mnuAddNewReceiptActionPerformed

    private void tbrListReceiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrListReceiptsActionPerformed
        ListReceiptsPane pane = new ListReceiptsPane();

        tpnBoard.addTab("Danh sách biên lai", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrListReceiptsActionPerformed

    private void mnuListReceiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListReceiptsActionPerformed
        tbrListReceiptsActionPerformed(evt);
    }//GEN-LAST:event_mnuListReceiptsActionPerformed

    private void mnuAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutUsActionPerformed
        AboutUsDialog dialog = new AboutUsDialog(this, true);

        dialog.setVisible(true);
    }//GEN-LAST:event_mnuAboutUsActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        dispose();
        LoginDialog dialog = new LoginDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void mnuLockupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLockupActionPerformed
        mnuLogoutActionPerformed(evt);
    }//GEN-LAST:event_mnuLockupActionPerformed

    private void tbrLockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrLockActionPerformed
        mnuLogoutActionPerformed(evt);
    }//GEN-LAST:event_tbrLockActionPerformed


    private void mnuAddExpenditureTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddExpenditureTypeActionPerformed
        AddExpenditureTypePane pane = new AddExpenditureTypePane(this);

        tpnBoard.addTab("Thêm loại chi tiêu", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_mnuAddExpenditureTypeActionPerformed

    public void showListExpenditures() {
        tbrListExpenditureActionPerformed(null);
    }

    public void showEditExpenditure(int id) {
        UpdateExpenditurePane pane = new UpdateExpenditurePane(this, id);

        tpnBoard.addTab("Chỉnh sửa chi tiêu", pane);
        tpnBoard.setSelectedComponent(pane);
    }

    public void showUpdateExpenditureType(int id) {
        UpdateExpenditureTypePane pane = new UpdateExpenditureTypePane(this, id);

        tpnBoard.addTab("Chinh sửa loại chi tiêu", pane);
        tpnBoard.setSelectedComponent(pane);
    }

    public void showListExpenditureTypes() {
        ListExpenditureTypesPane pane = new ListExpenditureTypesPane(this);

        tpnBoard.addTab("Danh sách loại chi tiêu", pane);
        tpnBoard.setSelectedComponent(pane);
    }

    private void mnuListExpenditureTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListExpenditureTypesActionPerformed
        showListExpenditureTypes();
    }//GEN-LAST:event_mnuListExpenditureTypesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(false);
                LoginDialog dialog = new LoginDialog(null, true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JMenuItem mnuAboutUs;
    private javax.swing.JMenuItem mnuAddExpenditure;
    private javax.swing.JMenuItem mnuAddExpenditureType;
    private javax.swing.JMenuItem mnuAddNewReceipt;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuListExpenditure;
    private javax.swing.JMenuItem mnuListExpenditureTypes;
    private javax.swing.JMenuItem mnuListReceipts;
    private javax.swing.JMenuItem mnuLockup;
    private javax.swing.JMenuItem mnuLogin;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JButton tbrAddExpenditure;
    private javax.swing.JButton tbrAddReceipt;
    private javax.swing.JButton tbrCloseTab;
    private javax.swing.JButton tbrListExpenditure;
    private javax.swing.JButton tbrListReceipts;
    private javax.swing.JButton tbrLock;
    private javax.swing.JTabbedPane tpnBoard;
    // End of variables declaration//GEN-END:variables
}
